"""Curated report content. Claims link to papers or official engineering sources."""

EVOLUTION = [
    {"period": "1990s–2008", "recall": "UserCF / ItemCF、共现倒排", "rank": "规则、流行度、LR", "shift": "从编辑规则转向群体行为", "limit": "稀疏、冷启动、覆盖率"},
    {"period": "2006–2013", "recall": "MF / 隐语义向量", "rank": "LR、GBDT、FM/FFM", "shift": "低维表示与自动特征交叉", "limit": "高阶非线性与时序不足"},
    {"period": "2013–2017", "recall": "DSSM 双塔 + ANN", "rank": "GBDT+LR、Wide&Deep、DeepFM", "shift": "召回—排序级联定型", "limit": "双塔交互弱、排序偏静态"},
    {"period": "2017–2020", "recall": "YouTube DNN、MIND、多兴趣", "rank": "DIN/DIEN、MMoE/PLE", "shift": "目标感知序列与多任务", "limit": "长序列成本、目标冲突"},
    {"period": "2018–2023", "recall": "SASRec/BERT4Rec、图与多模态", "rank": "Transformer、蒸馏、重排", "shift": "推荐成为行为序列建模", "limit": "训练服务一致性与算力"},
    {"period": "2023–2026", "recall": "TIGER / Semantic ID / HSTU-Match", "rank": "RankGPT、生成式列表打分", "shift": "OneRec/HSTU 尝试统一召排", "limit": "解码、合法性、更新与 ROI"},
]

MODELS = [
    {"id":"cf","chapter":"classic","stage":"经典","name":"协同过滤","idea":"从 user–item 共现估计相似度，以邻域投票召回或打分。","pros":"无需内容特征；解释直观；强基线。","cons":"稀疏和冷启动；热门偏置；全量相似度成本。","metric":"Recall@K / Coverage","notebook":"3_1_1_collaborative_filtering"},
    {"id":"mf","chapter":"classic","stage":"经典","name":"MF","idea":"把交互矩阵分解为用户与物品低维向量，内积重构偏好。","pros":"压缩稀疏矩阵；检索友好；易加入偏置。","cons":"依赖 ID；难用上下文和内容；内积表达受限。","metric":"RMSE / Recall@K","notebook":"3_1_2_matrix_factorization"},
    {"id":"fm","chapter":"classic","stage":"经典/排序","name":"FM","idea":"用特征隐向量内积参数化二阶交叉，线性时间计算全部 pair。","pros":"稀疏特征共享统计；少做手工交叉。","cons":"主要是二阶；不建模行为次序。","metric":"AUC / LogLoss","notebook":"3_1_3_factorization_machine"},
    {"id":"gbdtlr","chapter":"classic","stage":"排序","name":"GBDT+LR","idea":"树学习非线性分桶与组合，叶节点 one-hot 交给 LR 校准。","pros":"表格特征强；可解释；服务稳定。","cons":"两阶段；叶子空间膨胀且易陈旧。","metric":"AUC / LogLoss","notebook":"3_1_4_gbdt_lr"},
    {"id":"dssm","chapter":"retrieval","stage":"召回","name":"DSSM 双塔","idea":"用户塔、物品塔独立编码，同空间内积训练并用 ANN 全库检索。","pros":"item 可预计算；延迟低；可扩到亿级目录。","cons":"打分前无深交互；负采样偏差；单向量混兴趣。","metric":"Recall@K / MRR","notebook":"3_2_1_dssm"},
    {"id":"mind","chapter":"retrieval","stage":"召回","name":"MIND","idea":"动态路由把历史聚成多个兴趣胶囊，每个兴趣分别检索。","pros":"缓解兴趣混叠；覆盖多意图与长尾。","cons":"兴趣数敏感；多路 ANN 合并成本。","metric":"Recall@K / Coverage","notebook":"3_2_2_mind"},
    {"id":"deepfm","chapter":"ranking","stage":"排序","name":"DeepFM","idea":"FM 一二阶分支与 DNN 高阶分支共享 embedding 并联合训练。","pros":"端到端；兼顾记忆与泛化；成熟基线。","cons":"高阶交互隐式；无序列和去偏专门机制。","metric":"AUC / LogLoss","notebook":"3_3_1_deepfm"},
    {"id":"din","chapter":"ranking","stage":"排序","name":"DIN","idea":"用候选感知 attention 激活与当前物品相关的历史。","pros":"同一用户面对不同候选产生不同表示。","cons":"逐候选读取历史，延迟随候选数增长。","metric":"AUC / GAUC / P99","notebook":"3_3_2_din"},
    {"id":"dien","chapter":"ranking","stage":"排序","name":"DIEN","idea":"用辅助损失、GRU 与 AUGRU 显式学习兴趣状态及其演化。","pros":"利用顺序与兴趣变化；监督更密集。","cons":"训练与服务更复杂，校准和时延压力更高。","metric":"AUC / LogLoss / P99","notebook":"3_3_3_dien"},
    {"id":"mmoe","chapter":"multitask","stage":"多目标","name":"MMoE","idea":"每个任务用独立 gate 混合同一组共享专家。","pros":"共享灵活；适合相关任务。","cons":"专家塌缩、梯度冲突与样本空间错位。","metric":"逐任务 AUC + business value","notebook":"3_4_1_mmoe"},
    {"id":"ple","chapter":"multitask","stage":"多目标","name":"PLE","idea":"逐层分离共享与任务专属专家，控制知识共享边界。","pros":"缓解负迁移与跷跷板。","cons":"结构、参数和调参成本更高。","metric":"逐任务 AUC + transfer gap","notebook":"3_4_2_ple"},
    {"id":"sasrec","chapter":"retrieval","stage":"召回/Transformer","name":"SASRec","idea":"以因果自注意力编码真实行为序列，输出当前用户向量并预测下一物品。","pros":"并行训练；兼顾近期转移与较长依赖；可接全库检索。","cons":"注意力随序列长度平方增长；严格依赖时间协议。","metric":"HR@K / NDCG@K / P99","notebook":"3_2_3_sasrec"},
    {"id":"openonerec","chapter":"generative","stage":"生成式","name":"OpenOneRec","idea":"将 item/list token 化，自回归生成并用目录约束和奖励对齐。","pros":"统一列表目标；支持偏好优化。","cons":"无效 ID、重复、解码延迟与目录更新。","metric":"NDCG / invalid rate / P99","notebook":"4_2_openonerec_practice"},
    {"id":"hstu","chapter":"generative","stage":"生成式","name":"DLRM HSTU","idea":"把长期行为流作为统一序列进行 next-item 预训练与下游迁移。","pros":"长序列、统一表征和规模效应。","cons":"训练服务协同复杂，GPU ROI 要求高。","metric":"HR/NDCG + throughput / P99","notebook":"4_3_dlrm_hstu_practice"},
]

FRAMEWORKS = [
    {"axis":"定位","torcheasyrec":"大规模生产训练与服务配置","rechub":"轻量、统一 API 的研究/教学到部署"},
    {"axis":"易用性","torcheasyrec":"Protobuf/YAML 配置完整，但学习曲线较陡","rechub":"10–30 行可训练，Notebook 友好"},
    {"axis":"模型覆盖","torcheasyrec":"匹配、排序、多任务、生成式；含 HSTU-Match/ULTRA-HSTU","rechub":"30+；覆盖本应用所有经典深度模型及 HSTU/TIGER"},
    {"axis":"数据兼容","torcheasyrec":"CSV/Parquet、MaxCompute、Kafka，适合大数据管线","rechub":"DataGenerator/自定义 Dataset；PySpark/Parquet 可扩展"},
    {"axis":"工程能力","torcheasyrec":"TorchRec 分片、动态 embedding、AMP、TensorRT/AOTI","rechub":"统一 Trainer、追踪、ONNX、ANN/Milvus 插件"},
    {"axis":"代码质量信号","torcheasyrec":"Apache-2.0、配置 schema、测试与文档；阿里生产导向","rechub":"MIT、592+ commits、测试/benchmark/docs；社区维护活跃"},
    {"axis":"本项目选择","torcheasyrec":"工业配置档、HSTU 扩展与上线清单","rechub":"默认 CPU 实验后端，保证 Notebook 可读可跑"},
]

DATASETS = [
    {"name":"MovieLens latest-small","year":"2018 固定版本","scale":"100,836 ratings · 610 users · 9,742 movies","fit":"3.0—3.1 的 CF、MF、FM、GBDT+LR 教学","note":"结构简单，适合手算和经典基线；不再承担深度 CTR/序列实验","url":"https://files.grouplens.org/datasets/movielens/ml-latest-small-README.html"},
    {"name":"Amazon Reviews 2023 / Video Games","year":"2023","scale":"5-core: 94.8K users · 25.6K items · 814.6K reviews","fit":"DSSM、MIND、SASRec 电商召回与序列","note":"官方毫秒时间戳；仓库内切片保留 500 位最活跃用户的全部真实行为","url":"https://amazon-reviews-2023.github.io/data_processing/5core.html"},
    {"name":"KuaiRand-Pure","year":"2022","scale":"1.44M standard + 1.19M random-policy interactions","fit":"DeepFM、DIN/DIEN、MMoE/PLE、HSTU","note":"真实短视频曝光与 12 类反馈；包含随机干预，适合排序和多目标","url":"https://github.com/chongminggao/KuaiRand"},
    {"name":"MerRec","year":"2024","scale":"6 months, millions of C2C users/items","fit":"多动作、会话、电商多目标","note":"含 taxonomy、文本和买卖双重角色","url":"https://github.com/mercari/mercari-ml-merrec-pub-us"},
    {"name":"EB-NeRD","year":"2024","scale":"2.3M+ news users","fit":"新闻曝光、排序、多样性","note":"提供 demo/small/full，适合曝光偏差研究","url":"https://recsys.eb.dk/"},
    {"name":"Yambda-5B","year":"2025","scale":"4.79B events, 1M users, 9.39M tracks","fit":"工业级召回/排序/序列基础模型","note":"50M/500M/5B 三档；含 organic 标记和音频 embedding","url":"https://huggingface.co/datasets/yandex/yambda"},
    {"name":"Synerise UBM","year":"2025","scale":"multi-event retail logs, 1M target clients","fit":"通用行为表征、多任务","note":"购买/加购/移除/访问/搜索，Parquet","url":"https://recsys.synerise.com/summary"},
    {"name":"RecIF-Bench","year":"2025","scale":"100M interactions, 200K users","fit":"4.2 OpenOneRec 生成式召排","note":"短视频/广告/商品统一评测；遵循官方许可","url":"https://github.com/Kuaishou-OneRec/OpenOneRec"},
]

PRACTICES = [
    {"company":"YouTube / Google","system":"双塔候选生成 + 多任务排序；采样偏差校正","evidence":"A","lesson":"级联仍是可靠基线，训练负样本分布必须贴近全库。","url":"https://research.google/pubs/deep-neural-networks-for-youtube-recommendations/"},
    {"company":"Meta","system":"HSTU 序列生成；SilverTorch 索引即模型；基础模型迁移","evidence":"A","lesson":"模型—系统共设计，先以教师/表征迁移获取 ROI。","url":"https://github.com/meta-recsys/generative-recommenders"},
    {"company":"Netflix","system":"自回归用户交互基础模型连接首页、搜索等场景","evidence":"B","lesson":"共享用户表示能降低专用模型维护成本。","url":"https://netflixtechblog.com/foundation-model-for-personalized-recommendation-1a0bd8e02d39"},
    {"company":"快手","system":"OneRec 端到端列表生成；OpenOneRec + RecIF-Bench","evidence":"A","lesson":"奖励模型、DPO 与合法候选约束和模型本体同等重要。","url":"https://github.com/Kuaishou-OneRec/OpenOneRec"},
    {"company":"阿里巴巴","system":"MIND/DIN/DIEN/ESMM/PLE；TorchEasyRec 工程底座","evidence":"A","lesson":"多兴趣、多任务与流式特征在电商漏斗中长期共存。","url":"https://github.com/alibaba/TorchEasyRec"},
    {"company":"字节跳动","system":"Monolith 在线训练、无冲突哈希表与实时特征","evidence":"A","lesson":"推荐质量不仅取决于模型，在线新鲜度和一致性常是第一约束。","url":"https://arxiv.org/abs/2209.07663"},
    {"company":"腾讯","system":"PLE 多任务渐进式抽取","evidence":"A","lesson":"共享与专属专家分离可缓解任务负迁移。","url":"https://dl.acm.org/doi/10.1145/3383313.3412236"},
]

NOTEBOOKS = [
    {"slug":"3_0_math_foundations","title":"3.0A 数学基础：从矩阵到梯度下降","framework":"NumPy / Matplotlib","dataset":"MovieLens latest-small + 手算投影","runtime":"约 15 秒 CPU"},
    {"slug":"3_0_data_pipeline","title":"3.0B 数据与实验基础：从 import 到训练循环","framework":"pandas / PyTorch / inspect","dataset":"MovieLens latest-small 真实行为","runtime":"约 20 秒 CPU"},
    {"slug":"3_1_0_classic_foundations","title":"3.1 导读与数学基础：经典算法","framework":"NumPy / Matplotlib","dataset":"MovieLens latest-small","runtime":"约 10 秒 CPU"},
    {"slug":"3_1_1_collaborative_filtering","title":"3.1.1 协同过滤：UserCF / ItemCF","framework":"NumPy","dataset":"MovieLens latest-small","runtime":"约 20 秒 CPU"},
    {"slug":"3_1_2_matrix_factorization","title":"3.1.2 矩阵分解：BiasMF","framework":"PyTorch","dataset":"MovieLens latest-small","runtime":"约 30 秒 CPU"},
    {"slug":"3_1_3_factorization_machine","title":"3.1.3 因子分解机：FM","framework":"PyTorch / scikit-learn","dataset":"MovieLens latest-small 评分偏好任务","runtime":"约 30 秒 CPU"},
    {"slug":"3_1_4_gbdt_lr","title":"3.1.4 GBDT+LR","framework":"XGBoost / scikit-learn","dataset":"MovieLens latest-small 评分偏好任务","runtime":"约 30 秒 CPU"},
    {"slug":"3_1_summary","title":"3.1 总结：经典算法横向对比","framework":"结果聚合与选型","dataset":"MovieLens 真实实验 JSON","runtime":"约 10 秒 CPU"},
    {"slug":"3_2_0_retrieval_foundations","title":"3.2 导读与数学基础：向量召回","framework":"NumPy / Matplotlib","dataset":"Amazon Reviews 2023 Video Games","runtime":"约 10 秒 CPU"},
    {"slug":"3_2_1_dssm","title":"3.2.1 DSSM 双塔召回","framework":"Torch-RecHub DSSM","dataset":"Amazon Reviews 2023 电商行为","runtime":"约 20 秒 CPU"},
    {"slug":"3_2_2_mind","title":"3.2.2 MIND 多兴趣召回","framework":"Torch-RecHub MIND","dataset":"Amazon Reviews 2023 商品序列","runtime":"约 20 秒 CPU"},
    {"slug":"3_2_3_sasrec","title":"3.2.3 SASRec 序列召回","framework":"Torch-RecHub SASRec","dataset":"Amazon Reviews 2023 Video Games","runtime":"约 35 秒 CPU"},
    {"slug":"3_2_summary","title":"3.2 总结：DSSM、MIND 与 SASRec","framework":"结果聚合与选型","dataset":"Amazon Reviews 2023 实验 JSON","runtime":"约 5 秒 CPU"},
    {"slug":"3_3_0_ranking_foundations","title":"3.3 导读与数学基础：CTR 排序","framework":"NumPy / Matplotlib","dataset":"KuaiRand-Pure 真实曝光","runtime":"约 10 秒 CPU"},
    {"slug":"3_3_1_deepfm","title":"3.3.1 DeepFM 排序","framework":"Torch-RecHub DeepFM","dataset":"KuaiRand-Pure is_click","runtime":"约 20 秒 CPU"},
    {"slug":"3_3_2_din","title":"3.3.2 DIN 候选感知排序","framework":"Torch-RecHub DIN","dataset":"KuaiRand-Pure feed 序列","runtime":"约 25 秒 CPU"},
    {"slug":"3_3_3_dien","title":"3.3.3 DIEN 兴趣演化排序","framework":"Torch-RecHub DIEN","dataset":"KuaiRand-Pure feed 序列","runtime":"约 40 秒 CPU"},
    {"slug":"3_3_summary","title":"3.3 总结：DeepFM、DIN 与 DIEN","framework":"结果聚合与选型","dataset":"KuaiRand 实验 JSON","runtime":"约 5 秒 CPU"},
    {"slug":"3_4_0_multitask_foundations","title":"3.4 导读与数学基础：多目标学习","framework":"NumPy / Matplotlib","dataset":"KuaiRand-Pure 多反馈","runtime":"约 10 秒 CPU"},
    {"slug":"3_4_1_mmoe","title":"3.4.1 MMoE 多目标学习","framework":"Torch-RecHub MMOE","dataset":"KuaiRand is_click + long_view","runtime":"约 20 秒 CPU"},
    {"slug":"3_4_2_ple","title":"3.4.2 PLE 渐进式专家抽取","framework":"Torch-RecHub PLE","dataset":"KuaiRand is_click + long_view","runtime":"约 25 秒 CPU"},
    {"slug":"3_4_summary","title":"3.4 总结：MMoE 与 PLE","framework":"结果聚合与选型","dataset":"KuaiRand 实验 JSON","runtime":"约 5 秒 CPU"},
    {"slug":"4_0_generative_foundations","title":"4.0 导读与数学基础：生成式推荐","framework":"NumPy / Matplotlib","dataset":"KuaiRand-Pure","runtime":"约 10 秒 CPU"},
    {"slug":"4_1_generative_overview","title":"4.1 总结：生成式召回、排序与融合","framework":"结果聚合与工业选型","dataset":"KuaiRand 实验 JSON","runtime":"约 5 秒 CPU"},
    {"slug":"4_2_openonerec_practice","title":"4.2 OpenOneRec 实战","framework":"OpenOneRec 契约 + PyTorch 约束生成器","dataset":"KuaiRand taxonomy adapter；RecIF full 需授权","runtime":"smoke 1 分钟；全量需 GPU"},
    {"slug":"4_3_dlrm_hstu_practice","title":"4.3 DLRM HSTU 实战","framework":"Torch-RecHub HSTU + Meta DLRM-v3 配置","dataset":"KuaiRand-Pure 真实 feed 序列","runtime":"smoke 2 分钟；官方配置需 4×24GB GPU"},
]

CHAPTERS = {
    "foundations": {
        "number": "3.0", "title": "推荐算法数学基础：从表格、向量到模型训练",
        "intro": "为初次接触推荐算法的读者建立最低必要数学直觉：把行为写成矩阵，用向量衡量相似，用概率表达不确定性，再用损失函数和梯度下降让模型从错误中修正。",
        "layout": "从可手算的 3×4 用户—物品矩阵开始，依次理解向量、点积、余弦相似度、矩阵乘法、Sigmoid、LogLoss、梯度下降，以及 Recall/AUC 等评价指标。每个公式都配数字例子和图。",
        "use_cases": "这是 3.1—4.3 的共同先修课；不要求微积分或线性代数课程背景，只需掌握基础代数、函数和坐标系。",
        "model_ids": [], "opening": "3_0_math_foundations", "notebooks": ["3_0_math_foundations", "3_0_data_pipeline"], "summary": "3_0_data_pipeline",
        "sources": [
            ("MIT OpenCourseWare：Linear Algebra", "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/", "用于进一步理解向量、矩阵乘法与低秩表示；本章只提取推荐系统真正需要的部分。"),
            ("Google Machine Learning Crash Course：Logistic Regression", "https://developers.google.com/machine-learning/crash-course/logistic-regression", "用概率、Sigmoid 和 LogLoss 解释二分类预测，是 CTR 排序的数学起点。"),
            ("scikit-learn：Model evaluation", "https://scikit-learn.org/stable/modules/model_evaluation.html", "提供分类、回归和排序指标的正式定义；本章重点解释指标在推荐问题中的直觉。"),
        ],
    },
    "classic": {
        "number": "3.1", "title": "经典算法：协同过滤、MF、FM、GBDT+LR",
        "intro": "从显式邻域、低秩表示到稀疏特征交叉，建立召回与排序的四个最小原型。每个算法独立阅读与执行，最后只在相同任务口径内比较指标。",
        "layout": "先用小矩阵理解相似度与低秩，再进入真实 MovieLens Top-K/评分任务；随后把真实评分按阈值派生为二分类任务，比较 FM 与 GBDT+LR。",
        "use_cases": "ItemCF 适合相关推荐与兜底召回；MF 适合 ID 向量召回/评分；FM 与 GBDT+LR 适合稀疏表格 CTR 基线。",
        "model_ids": ["cf", "mf", "fm", "gbdtlr"],
        "opening": "3_1_0_classic_foundations",
        "notebooks": ["3_1_1_collaborative_filtering", "3_1_2_matrix_factorization", "3_1_3_factorization_machine", "3_1_4_gbdt_lr"],
        "summary": "3_1_summary",
        "sources": [
            ("Resnick et al., 1994：GroupLens 协同过滤", "https://dl.acm.org/doi/10.1145/192844.192905", "把群体评分压缩为邻域加权预测，是 UserCF 的早期系统证据。"),
            ("Sarwar et al., 2001：Item-based CF", "https://dl.acm.org/doi/10.1145/371920.372071", "把相似度转移到较稳定的 item 侧，奠定相关推荐与离线近邻表。"),
            ("Koren et al., 2009：Matrix Factorization", "https://datajobs.com/data-science-repo/Recommender-Systems-[Netflix].pdf", "以偏置加低秩向量解释评分结构，也是后续双塔内积的最小原型。"),
            ("Rendle, 2010：Factorization Machines", "https://www.csie.ntu.edu.tw/~b97053/paper/Rendle2010FM.pdf", "用共享隐向量估计稀疏二阶交叉，并将计算降到线性复杂度。"),
            ("He et al., 2014：GBDT+LR", "https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/", "树负责学习分桶与组合，LR 负责稀疏线性校准，形成经典两阶段 CTR 管线。"),
        ],
    },
    "retrieval": {
        "number": "3.2", "title": "召回模型：双塔、多兴趣与序列召回",
        "intro": "召回的核心约束是全库可检索。DSSM 以独立编码换取 ANN；MIND 用多个向量表达并行兴趣；SASRec 用因果自注意力表达兴趣随顺序的变化。",
        "layout": "先理解双塔、负采样与向量索引，再观察多兴趣抽取，最后学习 SASRec 的位置编码、因果注意力和 next-item 召回，统一比较 Recall、Coverage 与服务成本。",
        "use_cases": "DSSM 适合亿级目录通用召回；MIND 适合多意图用户；SASRec 适合时间顺序强、近期兴趣变化明显的内容与电商场景。",
        "model_ids": ["dssm", "mind", "sasrec"], "opening": "3_2_0_retrieval_foundations", "notebooks": ["3_2_1_dssm", "3_2_2_mind", "3_2_3_sasrec"], "summary": "3_2_summary",
        "sources": [("Huang et al., 2013：DSSM", "https://www.microsoft.com/en-us/research/publication/learning-deep-structured-semantic-models-for-web-search-using-clickthrough-data/", "以点击数据联合学习两侧表示，双塔的工程价值来自 item 向量可离线预计算。"), ("Li et al., 2019：MIND", "https://arxiv.org/abs/1904.08030", "动态路由从行为中抽取多个兴趣胶囊，用 label-aware attention 选择训练兴趣。"), ("Kang & McAuley, 2018：SASRec", "https://arxiv.org/abs/1808.09781", "用因果自注意力从有序历史产生 next-item 表示，可作为全库序列召回用户塔。")],
    },
    "ranking": {
        "number": "3.3", "title": "排序模型：DeepFM、DIN 与 DIEN",
        "intro": "排序在有限候选集上恢复深交互：DeepFM 处理静态交叉，DIN 让历史表示依赖候选，DIEN 再显式学习兴趣演化。",
        "layout": "从静态特征交叉基线进入候选感知注意力，再加入时序状态和辅助损失，统一比较 AUC、GAUC、LogLoss 与 P99。",
        "use_cases": "DeepFM 适合通用 CTR；DIN 适合强行为历史排序；DIEN 适合兴趣变化明显且收益覆盖时序成本的场景。",
        "model_ids": ["deepfm", "din", "dien"], "opening": "3_3_0_ranking_foundations", "notebooks": ["3_3_1_deepfm", "3_3_2_din", "3_3_3_dien"], "summary": "3_3_summary",
        "sources": [("Guo et al., 2017：DeepFM", "https://arxiv.org/abs/1703.04247", "共享 embedding 联合训练 FM 与 DNN，减少宽深模型的人工交叉。"), ("Zhou et al., 2018：DIN", "https://arxiv.org/abs/1706.06978", "候选感知激活历史，使同一用户对不同候选得到不同兴趣表示。"), ("Zhou et al., 2019：DIEN", "https://arxiv.org/abs/1809.03672", "用辅助损失监督兴趣抽取，再以目标感知 GRU 建模演化。")],
    },
    "multitask": {
        "number": "3.4", "title": "多目标模型：MMoE 与 PLE",
        "intro": "多目标学习的难点不是多加几个 loss，而是控制共享、专属知识与梯度冲突。MMoE 以任务门控选专家，PLE 进一步分层隔离。",
        "layout": "先建立 hard-sharing 对照，再观察 MMoE 的专家利用率和每任务 AUC，最后用 PLE 分析负迁移与跷跷板。",
        "use_cases": "适合联合 CTR、CVR、时长、互动和负反馈；任务相关性低或样本空间不同必须单独治理。",
        "model_ids": ["mmoe", "ple"], "opening": "3_4_0_multitask_foundations", "notebooks": ["3_4_1_mmoe", "3_4_2_ple"], "summary": "3_4_summary",
        "sources": [("Ma et al., 2018：MMoE", "https://dl.acm.org/doi/10.1145/3219819.3220007", "为每个任务学习门控，在共享专家上形成不同混合。"), ("Tang et al., 2020：PLE", "https://dl.acm.org/doi/10.1145/3383313.3412236", "逐层分离共享与任务专属专家，针对负迁移和跷跷板优化。")],
    },
    "generative": {
        "number": "4", "title": "生成式推荐：生成召回、排序与召排融合",
        "intro": "生成式推荐把 item、Semantic ID 或列表当作输出序列，探索从生成候选、生成排列到端到端 session 生成的统一路径。",
        "layout": "先比较 TIGER、生成式排序与 OneRec/HSTU 的任务边界，再分别通过 OpenOneRec 和 DLRM HSTU 实战验证合法解码、列表指标与序列契约。",
        "use_cases": "适合跨域统一建模、长序列和语义冷启；必须同时评估无效 ID、重复率、目录更新、P99 与 GPU ROI。",
        "model_ids": ["openonerec", "hstu"], "opening": "4_0_generative_foundations", "notebooks": ["4_2_openonerec_practice", "4_3_dlrm_hstu_practice"], "summary": "4_1_generative_overview",
        "sources": [("Rajput et al., 2023：TIGER", "https://arxiv.org/abs/2305.05065", "以 RQ-VAE Semantic ID 将全库召回转成受约束自回归生成。"), ("Kuaishou, 2025：OneRec / OpenOneRec", "https://github.com/Kuaishou-OneRec/OpenOneRec", "公开列表生成、奖励建模与 RecIF-Bench 流程，是召排融合的工业化样本。"), ("Zhai et al., 2024：HSTU", "https://arxiv.org/abs/2402.17152", "针对高基数、非平稳行为流重新设计序列转换与系统协同。")],
    },
}

SOURCES = [
    ("Collaborative Filtering","https://dl.acm.org/doi/10.1145/192844.192905","论文"),
    ("Matrix Factorization Techniques","https://datajobs.com/data-science-repo/Recommender-Systems-[Netflix].pdf","论文"),
    ("Factorization Machines","https://www.csie.ntu.edu.tw/~b97053/paper/Rendle2010FM.pdf","论文"),
    ("DSSM","https://www.microsoft.com/en-us/research/publication/learning-deep-structured-semantic-models-for-web-search-using-clickthrough-data/","论文/官方"),
    ("MIND","https://arxiv.org/abs/1904.08030","论文"),
    ("GBDT+LR at Facebook","https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/","论文/官方"),
    ("DeepFM","https://arxiv.org/abs/1703.04247","论文"),
    ("DIN","https://arxiv.org/abs/1706.06978","论文"),
    ("DIEN","https://arxiv.org/abs/1809.03672","论文"),
    ("MMoE","https://dl.acm.org/doi/10.1145/3219819.3220007","论文"),
    ("PLE","https://dl.acm.org/doi/10.1145/3383313.3412236","论文"),
    ("SASRec","https://arxiv.org/abs/1808.09781","论文"),
    ("SASRec official implementation","https://github.com/kang205/SASRec","官方代码"),
    ("BERT4Rec","https://arxiv.org/abs/1904.06690","论文"),
    ("TIGER","https://arxiv.org/abs/2305.05065","论文"),
    ("OneRec","https://arxiv.org/abs/2502.18965","论文"),
    ("OpenOneRec","https://github.com/Kuaishou-OneRec/OpenOneRec","官方代码"),
    ("HSTU","https://arxiv.org/abs/2402.17152","论文"),
    ("Meta Generative Recommenders","https://github.com/meta-recsys/generative-recommenders","官方代码"),
    ("TorchEasyRec","https://github.com/alibaba/TorchEasyRec","官方代码"),
    ("Torch-RecHub","https://github.com/datawhalechina/torch-rechub","官方代码"),
    ("Amazon Reviews 2023","https://amazon-reviews-2023.github.io/","官方数据"),
    ("KuaiRand","https://github.com/chongminggao/KuaiRand","官方数据/论文"),
    ("OpenOneRec RecIF-Bench","https://huggingface.co/datasets/OpenOneRec/OpenOneRec-RecIF","官方数据（需授权）"),
]
